{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ include "iam-chart.namespace" . }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.annotations.nginxSslRedirect }}"
    nginx.ingress.kubernetes.io/backend-protocol: "{{ .Values.ingress.annotations.nginxBackendProtocol }}"
    cert-manager.io/cluster-issuer: "{{ .Values.certificate.issuerRef.name }}"
spec:
  ingressClassName: "{{ .Values.ingress.className }}"
  tls:
    - hosts:
        - "localhost"
      secretName: "{{ include "iam-chart.fullname" . }}-tls"
  rules:
    - host: "localhost"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: "keycloak"
                port:
                  name: "http"
{{- end }}
