{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.auth.existingSecret }}
  namespace: {{ include "iam-chart.namespace" . }}
type: Opaque
data:
  {{ .Values.keycloak.auth.passwordSecretKey }}: ""
{{- end }}

{{- if .Values.postgresqlha.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresqlha.postgresql.existingSecret }}
  namespace: {{ include "iam-chart.namespace" . }}
type: Opaque
data:
  {{ .Values.postgresqlha.postgresql.passwordSecretKey }}: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresqlha.pgpool.existingSecret }}
  namespace: {{ include "iam-chart.namespace" . }}
type: Opaque
data:
  {{ .Values.postgresqlha.pgpool.adminPasswordSecretKey }}: ""
{{- end }}
