apiVersion: v2
name: iam-chart
description: >
  A Helm chart to deploy Keycloak with Sealed Secrets and PostgreSQL HA on Kubernetes.
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: keycloak
    version: 24.3.1
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: postgresql-ha
    version: 15.1.4
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: postgresqlha