auth:
  adminUser: "admin"
  existingSecret: "keycloak-admin-password"
  passwordSecretKey: "password"

production: true
proxy: edge
replicaCount: 1

resources:
    limits:
      cpu: 2
      memory: "1Gi"
    requests:
      cpu: 1
      memory: "512Mi"

externalDatabase:
  host: "postgresql-ha-pgpool.hbr-keycloak.svc.cluster.local"
  port: 5432
  user: "keycloak"
  password: null
  existingSecret: "postgresql-secret"
  existingSecretPasswordKey: "password"
  database: "keycloak"

postgresql:
  enabled: false
