global:
   # use 'kubectl get storageclass' to check for available storage classes
  storageClass: "standard"

postgresql:
  username: "keycloak"
  password: null
  existingSecret: "postgresql-secret"
  database: "keycloak"
  replicaCount: 2
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"

repmgr:
  password: null
  existingSecret: "postgresql-secret"

pgpool:
  adminUsername: "admin"
  adminPassword: null
  existingSecret: "pgpool-secret"
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "256m"
      memory: "128Mi"

metrics:
  enabled: false
  resources:
    limits:
      cpu: "500m"
      memory: "64Mi"
    requests:
      cpu: "250m"
      memory: "32Mi"

witness:
  create: false
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"

persistence:
  enabled: true
  size: "8Gi"